version: '3.8'

services:

  # ウェブサーバー
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nondelies_web
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./mysql-client.cnf:/etc/mysql/conf.d/client.cnf
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env   # ✅ ← これを追加（最重要）

  # PythonAPI
  python_api:
    build:
      context: ./python_api
      dockerfile: dockerfile.python
    container_name: nondelies_python
    ports:
      - "5000:5000"
    volumes:
      - ./python_api:/app
    env_file:
      - .env

  # データベース
  db:
    build:
      context: .
      dockerfile: dockerfile.db
    container_name: nondelies_db
    environment:
      MYSQL_ROOT_PASSWORD: 1017god25
      MYSQL_DATABASE: ndl_db
      MYSQL_USER: ndl_user
      MYSQL_PASSWORD: ndl_passwd
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
      - ./mysql-client.cnf:/etc/mysql/conf.d/client.cnf

volumes:
  db_data: